### PR TITLE
Fix main POST handler

### PR DESCRIPTION
**Pull request by valscion**
The `express.bodyParser()` already converts a JSON response to a populated object on `req.body`.

Hookshot crashed always when receiving a payload, because it tried to parse "undefined" with JSON.parse, failing `SyntaxError: Unexpected token u` on line 15.

### CODE REVIEW

**Comment by kdbanman** [comment]
+1. I discovered the same bug. This fix rectified it completely.

**Comment by konklone** [comment]
This fixes it for me too. @VesQ, thanks for doing this -- I'm going to use your fork until this is merged.

**Comment by coreh** [comment]
Sorry for the delay. Didn't see the original notifications. I was using `x-www-form-urlencoded` payloads, so that's why I didn't hit this. Merging.

**Comment by konklone** [comment]
Thank you!

**Pull request merged**
